services:
  anb-api:
    build: .
    container_name: anb-api
    networks:
      - web_net
    ports:
      - "8081:8081"
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      CELERY_BROKER_URL: redis://${REDIS_EC2_IP}:6379/0  # Cambiar a la IP de tu EC2
      CELERY_RESULT_BACKEND: redis://${REDIS_EC2_IP}:6379/0  # Cambiar a la IP de tu EC2
      S3_BUCKET: ${S3_BUCKET}
      S3_REGION: ${S3_REGION}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Asegúrate de tener este archivo de configuración
      - ./sites-available:/etc/nginx/sites-available
      - ./sites-enabled:/etc/nginx/sites-enabled
    ports:
      - "80:80"  # Abre el puerto 80 para acceso a través de HTTP
    networks:
      - web_net
    depends_on:
      - anb-api  # Asegúrate de que NGINX espere a que anb-api esté disponible

networks:
  web_net:
    driver: bridge
