services:
  celery-worker:
    build: .
    container_name: celery-worker
    environment:
      ENVIRONMENT: production
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: <RDS_ENDPOINT>
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      CELERY_BROKER_URL: redis://<REDIS_IP>:6379/0
      CELERY_RESULT_BACKEND: redis://<REDIS_IP>:6379/0
      S3_BUCKET: ${S3_BUCKET}
      S3_REGION: ${S3_REGION}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
    command: >
      pipenv run celery -A src.tasks.celery_worker worker --loglevel=info

networks:
  web_net:
    driver: bridge
