services: 
  db: 
    container_name: db-api
    image: "postgres:latest"
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - web_net
    ports: 
      - "5432:5432"
    volumes: 
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d db -U dbuser"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  web_net:
    driver: bridge

volumes: 
  pg-data: 
    driver: local