# Dockerfile_consumer
FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libpq-dev gcc python3-dev \
    && rm -rf /var/lib/apt/lists/*

ENV ENVIRONMENT=production
ENV AWS_REGION=us-east-1

COPY Pipfile Pipfile.lock ./
RUN pip install --no-cache-dir pipenv && pipenv install --system --deploy

# Copiar todo el código fuente incluyendo el consumer
COPY ./src /app/src

# Establecer el punto de entrada al consumidor
CMD ["python", "src/tasks/video_tasks/kinesis_consumer.py"]
