# Dockerfile_consumer
FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libpq-dev gcc python3-dev \
    && rm -rf /var/lib/apt/lists/*

ENV ENVIRONMENT=production
ENV AWS_REGION=us-east-1
ENV PYTHONPATH=/app
COPY Pipfile Pipfile.lock ./
RUN pip install --no-cache-dir pipenv && pipenv install --system --deploy

COPY ./src /app/src

CMD ["python", "src/tasks/video_tasks.py"]
