services:
  consumer:
    build:
      context: .
      dockerfile: Dockerfile_consumer
    container_name: kinesis_consumer
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      AWS_REGION: ${AWS_REGION}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
    networks:
      - kinesis_net
    restart: always
    command: ["python", "src/tasks/video_tasks.py"]

networks:
  kinesis_net:
    driver: bridge
