# Imagen base de Python
FROM python:3.12-slim

# Configuración del directorio de trabajo
WORKDIR /app

# Instalar dependencias del sistema necesarias
RUN apt-get update && apt-get install -y \
    libpq-dev gcc python3-dev \
    && rm -rf /var/lib/apt/lists/*

# Variables de entorno necesarias para el consumer
ENV AWS_REGION=us-east-1
ENV S3_BUCKET_NAME=your-s3-bucket
ENV S3_VIDEO_PREFIX=videos/
ENV KINESIS_STREAM_NAME=video-upload-stream
ENV DATABASE_URL=postgresql://dbuser:mypass@172.18.0.2:5432/db

# Copiar archivos de dependencias
COPY Pipfile Pipfile.lock ./

# Instalar dependencias
RUN python -m pip install --upgrade pip \
    && pip install --no-cache-dir pipenv \
    && pipenv install --system --deploy

# Copiar el código fuente
COPY ./src /app/src
COPY kinesis_consumer.py /app/kinesis_consumer.py

# Comando para ejecutar el consumer
CMD ["python", "kinesis_consumer.py"]
